"""Initial migration - Create sessions, messages, and brand_profiles tables

Revision ID: 001
Revises:
Create Date: 2026-01-28 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "paused", "completed", "archived", name="sessionstatus"),
            nullable=False,
        ),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "brand_profiles",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column(
            "industry",
            sa.Enum(
                "ecommerce",
                "saas",
                "fintech",
                "healthcare",
                "education",
                "retail",
                "manufacturing",
                "other",
                name="industrytype",
            ),
            nullable=True,
        ),
        sa.Column(
            "company_scale",
            sa.Enum(
                "startup", "small", "medium", "large", "enterprise", name="companyscale"
            ),
            nullable=True,
        ),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("target_age_range", sa.String(length=50), nullable=True),
        sa.Column("target_gender", sa.String(length=50), nullable=True),
        sa.Column("target_location", sa.String(length=255), nullable=True),
        sa.Column("brand_positioning", sa.Text(), nullable=True),
        sa.Column("brand_values", sa.Text(), nullable=True),
        sa.Column("brand_personality", sa.Text(), nullable=True),
        sa.Column("unique_selling_points", sa.Text(), nullable=True),
        sa.Column("main_products", sa.Text(), nullable=True),
        sa.Column("price_range", sa.String(length=100), nullable=True),
        sa.Column("marketing_channels", sa.Text(), nullable=True),
        sa.Column("competitors", sa.Text(), nullable=True),
        sa.Column("aeo_keywords", sa.Text(), nullable=True),
        sa.Column("content_strategy", sa.Text(), nullable=True),
        sa.Column("search_visibility_score", sa.Float(), nullable=True),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brand_profiles_name"), "brand_profiles", ["name"], unique=False
    )

    op.create_table(
        "messages",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", "system", "tool", name="messagerole"),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("text", "thinking", "tpaor", "output", "error", name="messagetype"),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("task", sa.Text(), nullable=True),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("observation", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("output_type", sa.String(length=50), nullable=True),
        sa.Column("output_data", sa.Text(), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("metadata", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["messages.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_index(op.f("ix_brand_profiles_name"), table_name="brand_profiles")
    op.drop_table("brand_profiles")
    op.drop_table("sessions")

    # Drop enum types
    op.execute("DROP TYPE IF EXISTS messagetype")
    op.execute("DROP TYPE IF EXISTS messagerole")
    op.execute("DROP TYPE IF EXISTS companyscale")
    op.execute("DROP TYPE IF EXISTS industrytype")
    op.execute("DROP TYPE IF EXISTS sessionstatus")
    # ### end Alembic commands ###
